Convert
AgueroMishel/rest-service pull request #1
Opened 2020-02-08 00:14 UTC by AgueroMishel

Adding Convert endpoint

2020-02-11 19:30 UTC, motenrique commented on src/main/java/com/restservice/Convert.java
> +    private final String stringNumber;
Este atributo solo es usado en el get y el constructor sin ser considerado en la lógica de conversión. Es correcto tenerlo o cuál es el objetivo principal de haberlo agregado?

2020-02-11 19:30 UTC, motenrique commented on src/main/java/com/restservice/Convert.java
> +public class Convert {
`Convert` es un nombre muy genérico para el propósito de esta clase

2020-02-11 19:30 UTC, motenrique commented on src/main/java/com/restservice/ConvertController.java
> +        return new Convert(number);
Aqui estás regresando un objeto `Convert`, lo que necesitamos es que se haga return del `int` con el formato de comma

2020-02-11 19:30 UTC, motenrique commented on src/main/java/com/restservice/ConvertController.java
> +            @RequestParam(value="integer") int number) {
Qué pasa si no paso algún numero en la URL? es decir, que solo entrase a algo así como `localhost:8080/convert`

2020-02-11 19:30 UTC, motenrique commented on src/main/java/com/restservice/Convert.java
> +    private final String stringNumber;
Justo acabo de ver como lo usas

2020-02-11 19:30 UTC, motenrique commented on src/main/java/com/restservice/Convert.java
> +    private final String stringNumber;
Con el actual diseño solamente puedes convertir un solo numero a string con comas. Cuál sería el inconveniente si tenemos por ejemplo 1000 `int` que deben ser convertidos a String?

2020-02-11 19:31 UTC, motenrique commented
Qué pasaría si deseamos agregar un conversor de int a String, pero esta vez queremos que el formato sea usando un punto? Cómo quedaría el diseño?

2020-02-18 05:36 UTC, motenrique requested changes

2020-02-18 05:36 UTC, motenrique commented on src/main/java/Formatters/Enums/IntegerFormat.java
> +    private String stringValue;
Creo que `value` y `stringValue` son nombres muy genéricos, incluso porque ambos atributos son de tipo `String`. Estos deben reflejar su propósito

2020-02-18 05:36 UTC, motenrique commented on src/main/java/Formatters/IntegerFormatter.java
> +    private IntegerFormatter() {}
Cuál es el propósito del constructor privado para esta clase?

2020-02-18 05:36 UTC, motenrique commented on src/main/java/com/restservice/BasicErrorController.java
> +public class BasicErrorController {
Cual es el propósito de esta clase?

2020-02-18 05:36 UTC, motenrique commented on src/main/java/com/restservice/IntegerFormatterController.java
> +//    @RequestMapping("/")
Evita el código comentado

2020-02-18 05:36 UTC, motenrique commented on src/main/java/com/restservice/IntegerFormatterController.java
> +    public String[][] format(
Porqué el uso de arrays en lugar de listas?

2020-02-18 05:36 UTC, motenrique commented on src/main/java/com/restservice/IntegerFormatterController.java
> +        }
Cuál es la complejidad de este bloque de código?

2020-02-18 19:31 UTC, AgueroMishel commented on src/main/java/com/restservice/Convert.java
> +    private final String stringNumber;
Cambié el método `GET` por `POST`. Ahora podrás enviar un `json` son la lista de números y formatos que desees

2020-02-18 19:31 UTC, AgueroMishel commented on src/main/java/com/restservice/Convert.java
> +public class Convert {
Ahora es: `IntegerFormatter`

2020-02-18 19:32 UTC, AgueroMishel commented on src/main/java/com/restservice/ConvertController.java
> +        return new Convert(number);
Ahora regresa un array de arrays de Strings

2020-02-18 19:33 UTC, AgueroMishel commented on src/main/java/com/restservice/ConvertController.java
> +            @RequestParam(value="integer") int number) {
Ya no aplica

2020-02-18 19:39 UTC, AgueroMishel commented on src/main/java/Formatters/IntegerFormatter.java
> +    private IntegerFormatter() {}
Es para evitar que se creen instancias de la clase, no tiene mucho sentido que se creen instancias de esa clase, cada vez que quieras llamar al método `format`, por eso lo hice `static` e hice el constructor privado

2020-02-18 19:42 UTC, AgueroMishel commented on src/main/java/com/restservice/BasicErrorController.java
> +public class BasicErrorController {
Typo

2020-02-18 19:43 UTC, AgueroMishel commented on src/main/java/com/restservice/IntegerFormatterController.java
> +//    @RequestMapping("/")
Typo

2020-02-18 21:00 UTC, AgueroMishel commented on src/main/java/com/restservice/IntegerFormatterController.java
> +    public String[][] format(
Cambio listo

2020-02-18 21:07 UTC, AgueroMishel commented on src/main/java/Formatters/Enums/IntegerFormat.java
> +    private String stringValue;
Se agregaron nuevas propuestas

2020-02-18 21:08 UTC, AgueroMishel commented
> Qué pasaría si deseamos agregar un conversor de int a String, pero esta vez queremos que el formato sea usando un punto? Cómo quedaría el diseño?

Se agregó un field dentro del `json` para indicar que tipo de formato se desea

2020-02-18 21:59 UTC, AgueroMishel commented on src/main/java/com/restservice/IntegerFormatterController.java
> +        }
**Linear Time:** O(n)

2020-02-25 23:41 UTC, motenrique approved these changes

2020-02-27 00:41 UTC, merged