ConvertTests
AgueroMishel/rest-service pull request #2
Opened 2020-02-11 00:06 UTC by AgueroMishel

Adding Convert tests

2020-03-24 17:04 UTC, motenrique requested changes

2020-03-24 17:04 UTC, motenrique commented on src/test/java/com/restservice/IntegerFormatterTests.java
> +        }
Esta funcion puede ser remplazada por el uso del método `contains` de la interface List

2020-03-24 17:04 UTC, motenrique commented on src/test/java/com/restservice/WebLayerTest.java
> +//@RunWith(SpringRunner.class)
Evita código comentado

2020-03-24 17:04 UTC, motenrique commented on src/main/java/com/restservice/HomeController.java
> +public class HomeController {
Este endpoint es solo para testing?

2020-04-03 17:54 UTC, AgueroMishel commented on src/test/java/com/restservice/IntegerFormatterTests.java
> +        }
Corregido en siguiente commit

2020-04-03 17:55 UTC, AgueroMishel commented on src/test/java/com/restservice/WebLayerTest.java
> +//@RunWith(SpringRunner.class)
Corregido en el siguiente commit

2020-04-03 17:55 UTC, AgueroMishel commented on src/main/java/com/restservice/HomeController.java
> +public class HomeController {
Sí. Qué te gustaría que hiciéramos con esto?

2020-05-04 21:48 UTC, AgueroMishel commented on src/main/java/com/restservice/HomeController.java
> +public class HomeController {
Se han removido los tests innecesario del branch

2020-07-03 20:29 UTC, merged